<?php
	
	
	
	
$field_repeater_overlay_array = array ( //======================================== Repeater (Overlay)
					'key' => 'field_57a4d86c44a1c',
					'label' => 'Overlay',
					'name' => 'overlay',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_Section_type_selector',
								'operator' => '==',
								'value' => 'normal',
							),
						),
					),
					'wrapper' => array (
						'width' => 100,
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_overlay_description',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => 'Add Overlay',
					'sub_fields' => array (
						array ( // ---------------------------------- Field (Sub Section Active)
							'key' => 'field_57a774a6286ee',
							'label' => 'Overlay Active',
							'name' => 'sub_section_active',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '10',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array ( // ---------------------------------- Field (Overlay Description)
							'key' => 'field_overlay_description',
							'label' => 'Overlay Description',
							'name' => 'overlay_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array ( // ################################## Tab (Overlay Tab Content)
							'key' => 'field_overlay_tab_position',
							'label' => 'Position',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array ( // ---------------------------------- Field (Left Space)
							'key' => 'field_57a79e5091df8',
							'label' => 'Left Space',
							'name' => 'left_position',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 100,
							'step' => '',
						),
						array ( // ---------------------------------- Field (Top Space)
							'key' => 'field_57a79ecb91dfc',
							'label' => 'Top Space',
							'name' => 'top_position',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 100,
							'step' => '',
						),
						array ( // ---------------------------------- Field (Overlay Width)
							'key' => 'field_57a79ea891df9',
							'label' => 'Overlay Width',
							'name' => 'overlay_width',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 100,
							'step' => '',
						),
						array ( // ---------------------------------- Field (Overlay Height)
							'key' => 'field_57a79eca91dfb',
							'label' => 'Overlay Height',
							'name' => 'overlay_height',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 100,
							'step' => '',
						),
	
						array ( // ################################## Tab (Overlay Tab Content)
							'key' => 'field_overlay_tab_content',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array ( // ---------------------------------- Field (Overlay Type Selector)
							'key' => 'field_Overlay_type_selector',
							'label' => 'Overlay Type Selector',
							'name' => 'Overlay_type_selector',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'normal' => 'Normal',
								'widgetarea' => 'Widget Area',
							),
							'default_value' => array (
								0 => 'normal',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),	
						array ( // ---------------------------------- Field (Text)
							'key' => 'field_57a79e0191df7',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_Overlay_type_selector',
										'operator' => '==',
										'value' => 'normal',
									),
								),
							),
							'wrapper' => array (
								'width' => '100',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => 'br',
							'readonly' => 0,
							'disabled' => 0,
						),
						array ( // ---------------------------------- Field (Text Color)
							'key' => 'field_57a8afe47059b',
							'label' => 'Text Color',
							'name' => 'text_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_Overlay_type_selector',
										'operator' => '==',
										'value' => 'normal',
									),
								),
							),
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'#000000' => 'Black',
								'#FFFFFF' => 'White',
								'#FF4F00' => 'CS-Orange',
								'transparent' => 'Transparent',
							),
							'default_value' => array (
								0 => '#000000',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array ( // ---------------------------------- Field (Text Align)
							'key' => 'field_57b3810acf75d',
							'label' => 'Text Align',
							'name' => 'text_align',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_Overlay_type_selector',
										'operator' => '==',
										'value' => 'normal',
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'lefttop' => 'Left Top',
								'leftmiddle' => 'Left Middle',
								'leftbottom' => 'Left Bottom',
								'centertop' => 'Center Top',
								'centermiddle' => 'Center Middle',
								'centerbottom' => 'Center Bottom',
								'righttop' => 'Right Top',
								'rightmiddle' => 'Right Middle',
								'rightbottom' => 'Right Bottom',
							),
							'default_value' => array (
								0 => 'left',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array ( // ---------------------------------- Field (Font Weight)
							'key' => 'field_57a8efa7ac69f',
							'label' => 'Font Weight',
							'name' => 'font_weight',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_Overlay_type_selector',
										'operator' => '==',
										'value' => 'normal',
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'normal' => 'Normal',
								'bold' => 'Bold',
							),
							'default_value' => array (
								0 => 'normal',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array ( // ---------------------------------- Field (Font Size)
							'key' => 'field_57a8eae38cf1a',
							'label' => 'Font Size',
							'name' => 'font_size',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_Overlay_type_selector',
										'operator' => '==',
										'value' => 'normal',
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '0.1',
							'max' => 50,
							'step' => '0.1',
						),
						array ( // ---------------------------------- Field (Line Height)
							'key' => 'field_57a8f3f39a79a',
							'label' => 'Line Height',
							'name' => 'line_height',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_Overlay_type_selector',
										'operator' => '==',
										'value' => 'normal',
									),
								),
							),
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '0.1',
							'max' => 50,
							'step' => '0.1',
						),
							array ( // ---------------------------------- Field (Overlay Padding)
							'key' => 'field_overlay_padding',
							'label' => 'Overlay Padding',
							'name' => 'overlay_padding',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array ( // ---------------------------------- Field (Link Type)
							'key' => 'field_overlay_link_type',
							'label' => 'Link Type',
							'name' => 'link_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_Overlay_type_selector',
										'operator' => '==',
										'value' => 'normal',
									),
								),
							),
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'None',
								'onsite' => 'On Site',
								'offsite' => 'Off Site',
							),
							'default_value' => array (
								0 => 'none',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
							),
							array ( // ---------------------------------- Field (Link On Site)
							'key' => 'field_overlay_link_on_site',
							'label' => 'Link On Site',
							'name' => 'link_on_site',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_overlay_link_type',
										'operator' => '==',
										'value' => 'onsite',
									),
								),
							),
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 1,
							'allow_archives' => 1,
							'multiple' => 0,
							),
							array ( // ---------------------------------- Field (Link Off Site)
							'key' => 'field_overlay_link_offsite',
							'label' => 'Link Off Site',
							'name' => 'link_off_site',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_overlay_link_type',
										'operator' => '==',
										'value' => 'offsite',
									),
								),
							),
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),

						array ( // ################################## Tab (Overlay Tab Background)
							'key' => 'field_overlay_tab_background',
							'label' => 'Background',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array ( // ---------------------------------- Field (Background Image)
							'key' => 'field_57a4d87d44a1d',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array ( // ---------------------------------- Field (Background Image Hover)
							'key' => 'field_overlay_background_image_hover',
							'label' => 'Background Image Hover',
							'name' => 'background_image_hover',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array ( // ---------------------------------- Field (Background Position)
							'key' => 'field_overlay_background_position',
							'label' => 'Background Position',
							'name' => 'background_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'center center' => 'Center Center',
								'bottom right' => 'Bottom Right',
								'bottom left' => 'Bottom Left',
								'bottom center' => 'Bottom Center',
							),
							'default_value' => array (
								0 => 'center center',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array ( // ---------------------------------- Field (Hover Layout)
							'key' => 'field_overlay_hover_layout',
							'label' => 'Hover Layout',
							'name' => 'hover_layout',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => $hover_layout_types,
							'default_value' => array (
								0 => 'none',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array ( // ---------------------------------- Field (Background Color)
							'key' => 'field_57b462f57120e',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'#000000' => 'Black',
								'#FFFFFF' => 'White',
								'#FF4F00' => 'CS-Orange',
								'#e7e7e7' => 'CS-Grey',
								'transparent' => 'Transparent',
							),
							'default_value' => array (
								0 => 'transparent',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array ( // ---------------------------------- Field (Background Image Size)
							'key' => 'field_overlay_background_image_size',
							'label' => 'Background Image Size',
							'name' => 'background_image_size',
							'type' => 'number',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 0,
							'max' => 100,
							'step' => '',
						),


					),
				);
	
	